import { useEffect, useState } from 'react';
import { ArrowRight, Check, MessageCircle, ShieldCheck, Trash2, Trophy, Users, X, Zap } from 'lucide-react';

export function Matches({ request, notify, setView }) {
  const [matches, setMatches] = useState([]);
  const [selected, setSelected] = useState(null);
  useEffect(() => { request('/matches').then((result) => setMatches(result.data?.matches || result.data || [])).catch((error) => notify(error.message)); }, [request, notify]);
  async function action(id, endpoint, body) {
    try { const result = await request(`/matches/${id}/${endpoint}`, { method: 'PUT', body: JSON.stringify(body || {}) }); setMatches((current) => current.map((match) => match._id === id ? (result.data?.match || match) : match)); notify('Match updated'); }
    catch (error) { notify(error.message || 'Could not update this match.'); }
  }
  return <div className="page fade-in"><div className="section-heading"><div><span className="eyebrow">SMART MATCHING</span><h3>Your possible matches</h3></div></div><div className="feature-list">{matches.length === 0 && <Empty title="No matches yet" text="When Foundly spots a strong connection, it will appear here." />}{matches.map((match) => <div className="feature-row" key={match._id}><div><span className="type-pill">{match.score}% match</span><h3>{match.lostItem?.title || 'Lost item'} <span className="muted">with</span> {match.foundItem?.title || 'found item'}</h3><p>{(match.reasons || []).join(' · ') || 'Foundly found a few promising similarities.'}</p><small>Status: {match.status.replaceAll('_', ' ')}</small></div><div className="row-actions"><button className="small-btn" onClick={() => setSelected(match)}><MessageCircle size={15} /> Chat</button>{match.lostUserConfirmed ? null : <button className="small-btn" onClick={() => action(match._id, 'confirm-lost')}>Confirm lost</button>}{match.foundUserConfirmed ? null : <button className="small-btn" onClick={() => action(match._id, 'confirm-found')}>Confirm found</button>}<button className="icon-btn" onClick={() => action(match._id, 'reject')}><X size={16} /></button></div></div>)}</div>{selected && <Chat match={selected} request={request} notify={notify} onClose={() => setSelected(null)} />}</div>;
}

export function Chat({ match, request, notify, onClose }) {
  const [messages, setMessages] = useState([]); const [message, setMessage] = useState('');
  useEffect(() => { request(`/matches/${match._id}/messages`).then((result) => setMessages(result.data?.messages || [])).catch((error) => notify(error.message)); }, [match._id, request, notify]);
  async function send(event) { event.preventDefault(); if (!message.trim()) return; try { const result = await request(`/matches/${match._id}/messages`, { method: 'POST', body: JSON.stringify({ message }) }); setMessages((current) => [...current, result.data.message]); setMessage(''); } catch (error) { notify(error.message || 'Message could not be sent.'); } }
  return <div className="modal-backdrop"><div className="chat-panel"><div className="chat-head"><div><span className="eyebrow">PRIVATE HANDOVER CHAT</span><h3>{match.lostItem?.title || 'Match conversation'}</h3></div><button className="icon-btn" onClick={onClose}><X size={17} /></button></div><div className="messages">{messages.length === 0 && <Empty title="Start the conversation" text="Coordinate a safe campus handover here." />}{messages.map((entry) => <div className="message" key={entry._id}><strong>{entry.sender?.name || 'Member'}</strong><p>{entry.message}</p></div>)}</div><form className="message-form" onSubmit={send}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a message..." /><button className="primary-btn"><ArrowRight size={16} /></button></form></div></div>;
}

export function Claims({ request, notify }) {
  const [claims, setClaims] = useState([]);
  useEffect(() => { request('/claims/my').then((result) => setClaims(result.data?.claims || [])).catch((error) => notify(error.message)); }, [request, notify]);
  return <div className="page narrow-page fade-in"><span className="eyebrow">YOUR CLAIMS</span><h1 className="feature-title">The things<br /><em>you’re looking for.</em></h1><div className="feature-list">{claims.length === 0 && <Empty title="No claims yet" text="When you recognize a found item, your claim history will live here." />}{claims.map((claim) => <div className="feature-row" key={claim._id}><div><span className={`type-pill ${claim.status}`}>{claim.status}</span><h3>{claim.item?.title || 'Item claim'}</h3><p>{claim.description}</p><small>Owner: {claim.owner?.name || 'Campus member'}</small></div><ShieldCheck size={20} className="muted" /></div>)}</div></div>;
}

export function RealRewards({ request, notify, user }) {
  const [data, setData] = useState({ rewards: [], leaderboard: [] });
  useEffect(() => { Promise.all([request('/rewards?limit=20'), request('/rewards/leaderboard')]).then(([history, board]) => setData({ rewards: history.data?.rewards || [], leaderboard: board.data?.leaderboard || [] })).catch((error) => notify(error.message)); }, [request, notify]);
  return <div className="page fade-in"><div className="rewards-head"><div><span className="eyebrow">THE ROLL OF HONOR</span><h1>Good looks<br /><em>good on you.</em></h1><p>Every small act makes campus feel more like a community.</p></div><div className="points-orbit"><div><span>YOUR SCORE</span><strong>{user.rewardPoints || 0}</strong><small>points</small></div></div></div><div className="feature-columns"><section><div className="section-heading"><div><span className="eyebrow">ACTIVITY</span><h3>Recent points</h3></div></div><div className="feature-list compact">{data.rewards.length === 0 && <Empty title="No points yet" text="Your good deeds will be recorded here." />}{data.rewards.map((reward) => <div className="feature-row" key={reward._id}><div><h3>{reward.description}</h3><small>{reward.action}</small></div><strong className="points-plus">+{reward.points}</strong></div>)}</div></section><section><div className="section-heading"><div><span className="eyebrow">COMMUNITY</span><h3>Leaderboard</h3></div></div><div className="feature-list compact">{data.leaderboard.slice(0, 8).map((member, index) => <div className="feature-row" key={member._id}><div className="rank">{index + 1}</div><div><h3>{member.name}</h3><small>{member.department || 'Campus member'}</small></div><strong>{member.rewardPoints}</strong></div>)}</div></section></div></div>;
}

export function AdminDashboard({ request, notify }) {
  const [stats, setStats] = useState(null); const [tab, setTab] = useState('overview'); const [rows, setRows] = useState([]);
  useEffect(() => { request('/admin/stats').then((result) => setStats(result.data)).catch((error) => notify(error.message)); }, [request, notify]);
  useEffect(() => { if (tab === 'overview') return; const path = tab === 'users' ? '/admin/users' : tab === 'items' ? '/admin/items' : '/admin/claims'; request(path).then((result) => setRows(result.data?.[tab] || [])).catch((error) => notify(error.message)); }, [tab, request, notify]);
  async function moderate(id, status) { try { await request(`/admin/claims/${id}`, { method: 'PUT', body: JSON.stringify({ status }) }); notify(`Claim ${status}`); setRows((current) => current.filter((row) => row._id !== id)); } catch (error) { notify(error.message); } }
  return <div className="page fade-in"><span className="eyebrow">OPERATIONS</span><h1 className="feature-title">Keep campus<br /><em>moving safely.</em></h1><div className="admin-tabs">{['overview', 'users', 'items', 'claims'].map((name) => <button className={tab === name ? 'selected' : ''} key={name} onClick={() => setTab(name)}>{name}</button>)}</div>{tab === 'overview' && stats && <div className="admin-stats"><Stat icon={<Users />} label="Members" value={stats.totalUsers} /><Stat icon={<Zap />} label="Open items" value={stats.openItems} /><Stat icon={<Check />} label="Resolved" value={stats.resolvedItems} /><Stat icon={<Trophy />} label="Resolution rate" value={`${stats.resolutionRate}%`} /></div>}{tab !== 'overview' && <div className="feature-list">{rows.map((row) => <div className="feature-row" key={row._id}><div><h3>{row.name || row.title || row.item?.title || 'Record'}</h3><p>{row.email || row.description || row.status || row.category || 'Active record'}</p></div>{tab === 'claims' && row.status === 'pending' && <div className="row-actions"><button className="small-btn" onClick={() => moderate(row._id, 'approved')}><Check size={15} /> Approve</button><button className="small-btn danger" onClick={() => moderate(row._id, 'rejected')}><Trash2 size={15} /> Reject</button></div>}</div>)}{rows.length === 0 && <Empty title="Nothing here yet" text="New records will appear as the community uses Foundly." />}</div>}</div>;
}
function Stat({ icon, label, value }) { return <div className="stat-card">{icon}<span>{label}</span><strong>{value}</strong></div>; }
function Empty({ title, text }) { return <div className="empty-state"><MessageCircle size={26} /><h3>{title}</h3><p>{text}</p></div>; }
